### ISSUE TITLE
ConfigPath : if wrong no error is raised

### ISSUE THREAD

**Issue by soleil-ica** [esrf-bliss/Lima-camera-maxipix#1] opened 2016-06-28 11:30 UTC
If the config path doesn't exist, no error is thrown, then the plugin seems OK, but in fact it is not as the config is not loaded

**Comment by laurent-claustre** [comment] 2016-07-07 14:15
I found the problem, it comes from the tools file MpxCommon.cpp and checkPath() function which throws an exception LIMA_EXEC, but the exception is ignored !!!!
I'm investigating....

**Comment by laurent-claustre** [comment] 2016-07-11 13:46
The issue is now fixed,

**Closed as completed by laurent-claustre** 2016-07-11 13:46 UTC
